version: '3.1'

services:

  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Shop.Services.Catalog/Shop.Services.Catalog.WebAPI/Dockerfile

  basket.api:
    image: basketapi
    build: 
      context: .
      dockerfile: Services/Shop.Services.Basket/Shop.Services.Basket.WebAPI/Dockerfile

  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  elasticsearch-data:
